
name: "Custom analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  analyze:
    name: Custom tool
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload sarif as alerts
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports/report.sarif
        
    - name: Upload report.xml
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: report.xml
        # A file, directory or wildcard pattern that describes what to upload
        path: reports/report.xml
